<% DB_TYPE='mysql2'%>

common: &common
 adapter: <%= DB_TYPE %>
 encoding: utf8
 reconnect: false
 pool: 5
 username: root
 password: 

development:
 <<: *common
 database: asana_development

test:
 <<: *common
 database: asana_test

production:
 <<: *common
 database: asana_production
